version: '3.9'

services:
  postgresql-crypto-db:
    image: 'postgres:latest'
    container_name: 'postgresql-crypto-db'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-crypto-db-volume:/data/postgres/crypto-db

  liquibase:


  crypto-balance-tracker-login:
    image: 'crypto-balance-tracker-login:latest'
    container_name: 'crypto-balance-tracker-login'
    depends_on:
      - postgresql-crypto-db
    environment:
      - POSTGRESQL_DATABASE=postgres
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - ENV_PROFILE=docker
    ports:
      - '8081:8081'

  crypto-balance-tracker:
    image: 'crypto-balance-tracker:latest'
    container_name: 'crypto-balance-tracker'
    depends_on:
      - postgresql-crypto-db
      - crypto-balance-tracker-login
    environment:
      - POSTGRESQL_DATABASE=postgres
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DEMO_COINGECKO_API_KEY=${DEMO_COINGECKO_API_KEY}
      - PRO_COINGECKO_API_KEY=${PRO_COINGECKO_API_KEY}
      - ENV_PROFILE=docker
    ports:
      - '8080:8080'

  crypto-balance-tracker-ui:
    image: 'crypto-balance-tracker-ui:latest'
    container_name: 'crypto-balance-tracker-ui'
    depends_on:
      - crypto-balance-tracker
    ports:
      - '5173:5173'

volumes:
  crypto-db-volume:
